from heichblatt/jenkins-slave
maintainer heichblatt
run /usr/bin/yum install -y which tar
run gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 && \
    curl -sSL https://get.rvm.io | bash -s -- --ruby=2.2